### ISSUE TITLE
Write test cases

### ISSUE THREAD

**Issue by xuezhou1998** [NYUDevopsInventoryTeam/inventory#12]
**As a** developer  
**I need** to write test cases   
**So that** I can test our services and model   

**Details & Assumptions:** 
* Create the TDD `test_xxx.py` files that contains the Unit Tests to test our services and model
* Write test cases for each of Create, Read, Update, Delete, List, Query, and Action
* Use the standard PyUnit syntax
* Use the coverage tool to measure tests and ensure coverage is at least 95%

**Acceptance Criteria:**

```gherkin
Given the developed code is complete
When I finish writing test cases 
Then I could add them into ./tests folder and use them to test our services and model
```

**Comment by eva23511** [comment]
Don't need stories to write test cases, because every story is assumed to be tested.
