### ISSUE TITLE
Create a models.py ﬁle

### ISSUE THREAD

**Issue by walkccc** [NYUDevopsInventoryTeam/inventory#5]
**As a** developer  
**I need** to create `models.py`
**So that** I can hold model definitions of the resource

**Details & Assumptions:** 
* Create a `models.py` file that holds model definitions of the resource

**Acceptance Criteria:**

```gherkin
Given the developed code is complete
When a user needs a model defined in models.py
Then they should be able to use it easily
```

**Comment by eva23511** [comment]
Duplicate of #14
