### ISSUE TITLE
Create loggers for .py files

### ISSUE THREAD

**Issue by haorann** [NYUDevopsInventoryTeam/inventory#8]
**As a** developer 
**I need** to log my actions  
**So that** we can debug easily especially when we get to the cloud deploy

**Details & Assumptions:** 
* Add loggers after every important actions

**Acceptance Criteria:**

```gherkin
Given loggers are added in every .py file properly
When something unexpected happens
Then I can check what’s going wrong
```

**Comment by eva23511** [comment]
Duplicate of #14
